### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kheeyaa** [kheeyaa/dev-jeans#43]
- [ ] 같은 이름의 이미지 업로드 안되는 버그
- [ ] 의상 색상 변경
- [ ] 아이템 z-index 기준으로 관리
